---
title: "Bio"
---

I grew up in Sharon, Pennsylvania, graduated from Sharon High School, and was honored to be inducted into its Hall of Fame in September 2017. I then attended college at the University of Pittsburgh. After graduating with dual degrees in Economics and Business, I earned the M.A. in Economics at Pennsylvania State University, a law degree from the University of Pittsburgh, and the Ph.D from the University of Chicago.

I am Professor of Political Science at Bocconi University, Director of Global Governance Partnerships at the SDA Bocconi School of Management, and Editor-in-Chief of the *Journal of Public Policy*. My work sits at the intersection of political science, public administration, and public policy, with a particular concern for how democratic institutions make public power accountable, effective, and legitimate.

I returned to Bocconi in 2026 after several years as the Sherwin-Whitmore Professor of Public Policy, Law, and Political Science at the Pennsylvania State University. I served as Professor of the Politics of Public Policy at New York University (2014-2018), where I was also Vice Dean for Academic Affairs and Research in the Robert F. Wagner School of Public Service. In Spring 2015, I was honored to hold the Jacob K. Javits Visiting Professorship at New York University. Between 2009-2014, I held the C.C. Crawford Chair in the Price School of Public Policy at the University of Southern California. My teaching career in public policy, public administration and political science has also brought me to the University of Kentucky, Texas A&M University, and the University of Georgia. 

Since December 2015, I am an elected fellow of the National Academy of Public Administration. I was uniquely honored to have been selected as the 2020 recipient of the Herbert Simon Award for career contributions to the Scientific Study of Bureaucracy.

Over my career, I have held secondary appointments as Senior Research Professor at the Barcelona Institute of International Studies (IBEI), Senior Lecturer in Politics at the University of Manchester and Professor of Public Policy Analysis in the School of Government and Society at the University of Birmingham. I was Honorary Senior Research Fellow in the Department of Political Science at University College London and have held similar affiliations at the University of Birmingham and Nottingham Trent University.

My research examines the ways in which politics shapes public policies and their implementation and what that means for democracy. I have been particularly interested in the relationship between public administration and democracy, and my book, *Democracy Administered: How Public Administration Shapes Representative Government* (Cambridge University Press) is my most ambitious work so far in that area. The research agenda in Chapter 5 of that book has now led to REPGOV, a project funded through a European Research Council Advanced Grant that began on January 1, 2022 in Barcelona. With Larry Lynn, to whom *Democracy Administered* is dedicated, I wrote *Madison’s Managers: Public Administration and the Constitution* (Johns Hopkins University Press). Written with Lindsey Schwartz, *Public Administration and Democracy: The Complementarity Principle* (Cambridge University Press), which embeds within democratic theory the principle of complementarity between political and administrative values within states that I offered in Chapter 6 of *Democracy Administered*.

I have written two books on policymaking in the United Kingdom, *Public Policy Investment: Priority-Setting and Conditional Representation in British Statecraft* (Oxford University Press) with my friend Peter John and *Policy Agendas in British Politics* (Palgrave) with Peter again, as well Will Jennings and Shaun Bevan.

My textbook, *The Political Economy of Public Sector Governance* (Cambridge University Press), is meant to introduce positive political theory to students of public policy and public administration.

My papers have appeared in a variety of scholarly journals including the *American Political Science Review*, *American Journal of Political Science, British Journal of Political Science, Journal of Politics, Journal of Theoretical Politics, Political Studies, Governance, Journal of Public Administration Research and Theory*, *Public Administration* and *Public Administration Review*. My Erdos number is 4.

I serve or have served on the editorial boards of the *Journal of Politics, British Journal of Political Science, Political Science Research and Methods*, *Journal of Public Administration Research and Theory*, and the *International Public Management Journal.* In November 2011, I became co-editor of the *Journal of Public Policy* with Peter John. I assumed the role of Senior Executive Editor in 2016, and in January 2023, I became Editor-in-Chief.

When not in Milan, I am at home in Philadelphia.
